### ISSUE TITLE
Frozen refresh behaviour at start

### ISSUE THREAD

**Issue by dannydaddy3** [xorshine/KafkaRefresh#8]
When pulling refresh its frozen until you reach some offset. When reached, it starts animating. Is this by design? 
It seems to me that expected behaviour is when pulling, you see how refresh is already animating, even if it's 1 pixel on screen.

I wanted to use this component, to not reinvent the wheel again, but this push me away. What do you think?

**Comment by xorshine** [comment]
I do not know your description, is it possible to screen the simulator? If I know, solve it immediately

**Comment by xorshine** [comment]
Send the recorded video to me or email me

**Comment by xorshine** [comment]
When the refresh control appears on the screen, even if there is only one pixel, you think the animation should start and I do not quite agree with your point of view. The reason is as follows:
1, KafkaRefresh there are several styles in the refresh control appears on the implementation of animations, there are indeed several styles are in the process of refreshing the animations, which is better for users are not refresh and refresh the two different status.
2, it is easy for me to make some changes, but will this change be better?
However, when the user is dragging, it is good to add some animation. I should think about how to add some animation

**Comment by dannydaddy3** [comment]
I just got that I understood it bad when explained to you. 
I agree that user have to separate when refresh is in active status or not, so actually what would be cool if when you pull the refresh it started to fill itself until you reach some offset where refresh actually starts. So exactly as behaviour of standard refresh or for example refresh on youtube app. When as you pull back and forth refresh will fill and unfill itself according offset.

So yeah, when dragging would be good to add some animation because it's familiar behaviour for users

**Comment by xorshine** [comment]
The original intention of this library open source is to solve the bugs I know of open source libraries. But your advice is very good, I will be in the next free time to add more animation. Thanks for your advice.
